name: Build

on:
  schedule:
    - cron: '0 0 10 * *'  # Runs on the first day of every month at midnight
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dotnet-outdated
      run: dotnet tool install --global dotnet-outdated-tool
    - name: Update NuGet Packages
      run: dotnet outdated --upgrade
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
