name: Build

on:
  schedule:
    - cron: '15 2 8/14 * *'  # Runs on the 8th day, repeat every 14 days at 02:15 (prevent 00:00 as capacity of Github might be reduced)
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      packages_updated: ${{ steps.check_packages.output.packages_updated }}  # Reference the output here

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dotnet-outdated
      run: dotnet tool install --global dotnet-outdated-tool

    - name: Update NuGet Packages
      id: check_packages  # Give this step an ID to reference its outputs
      run: |
        dotnet outdated --upgrade
        if [ -n "$(git status --porcelain)" ]; then
          echo "Packages updated."
          echo "packages_updated=true" >> $GITHUB_OUTPUT  # Set environment variable
        else
          echo "No package updates."
          echo "packages_updated=false" >> $GITHUB_OUTPUT  # Set environment variable
        fi

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        if [ "${{ steps.check_packages.output.packages_updated }}" == "true" ]; then 
          git add .
          git commit -m "Update NuGet packages"
          git push
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      if: steps.check_packages.output.packages_updated == 'true'  # Use environment variable for the condition
      run: dotnet build --no-restore

    - name: Test
      if: steps.check_packages.output.packages_updated == 'true'  # Use environment variable for the condition
      run: dotnet test --no-build --verbosity normal

    - name: Debug Output  # Debug step to log the value of packages_updated
      run: echo "Packages Updated:" ${{ steps.check_packages.output.packages_updated }}
