name: Build

on:
  schedule:
    - cron: '0 0 10 * *'  # Runs on the 10th day of every month at midnight
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      packages_updated: ${{ steps.check_packages.outputs.updated }}  # Reference the output here

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dotnet-outdated
      run: dotnet tool install --global dotnet-outdated-tool

    - name: Update NuGet Packages
      id: check_packages  # Give this step an ID to reference its outputs
      run: |
        dotnet outdated --upgrade
        if [ -n "$(git status --porcelain)" ]; then
          echo "Packages updated."
          echo "true" >> $GITHUB_ENV  # Use environment file to set updated status
        else
          echo "No package updates."
          echo "false" >> $GITHUB_ENV  # Use environment file to set updated status
        fi

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        if [ "$(cat packages_updated.txt)" == "true" ]; then
          git add .
          git commit -m "Update NuGet packages"
          git push
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      if: steps.check_packages.outputs.updated == 'true'  # Only run if packages were updated
      run: dotnet build --no-restore

    - name: Test
      if: steps.check_packages.outputs.updated == 'true'  # Only run if packages were updated
      run: dotnet test --no-build --verbosity normal
